Web_Project/Controllers/MenuController.cs
using BusinessLogic.Services;
using DataLayer.Enums;
using DataLayer.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;

namespace Web_Project.Controllers
{
    public class MenuController : Controller
    {
        private readonly IMenuService _service;
        public MenuController(IMenuService service)
        {
            _service = service;
        }

        public async Task<IActionResult> Index()
        {
            var menues = await _service.GetAll();
            return View(menues);
        }

        public async Task<ActionResult> FilterView(string category)
        {
            if(category != null)
            {
                BaseCategories myEnum = (BaseCategories)Enum.Parse(typeof(BaseCategories), category);
                var menuList = await _service.GetByCategory(myEnum);
                return PartialView(menuList);
            }
            else
            {
                var menuList = await _service.GetAll();
                return PartialView(menuList);
            }
        }

        public List<SelectListItem> GetRestaurants()
        {
            var lstRest = new List<SelectListItem>();
            var restaurants = _service.GetRestaurants();

            lstRest = restaurants.Select(c => new SelectListItem()
            {
                Value = c.Id.ToString(),
                Text = c.Name,
            }).ToList();

            var restItem = new SelectListItem()
            {
                Value = "",
                Text = "Select Restaurant"
            };

            lstRest.Insert(0, restItem);


            return lstRest;
        }

        public List<SelectListItem> GetProducts()
        {
            var lstProd = new List<SelectListItem>();
            var products = _service.GetProducts();

            lstProd = products.Select(c => new SelectListItem()
            {
                Value = c.Id.ToString(),
                Text = c.Name,
            }).ToList();

            var restItem = new SelectListItem()
            {
                Value = "",
                Text = "Select Products"
            };

            lstProd.Insert(0, restItem);


            return lstProd;
        }

        [HttpGet]
        public async Task<IActionResult> Create()
        {
            ViewBag.RestId = GetRestaurants();
            ViewBag.ProdId = GetProducts();
            SelectList categories = new SelectList(Enum.GetValues(typeof(BaseCategories)));
            ViewBag.Categories = categories;
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(CreateMenuVM menu)
        {
            if(ModelState.IsValid)
            {
                await _service.Add(menu);
                return RedirectToAction(nameof(Index));
            }
            ViewBag.RestId = GetRestaurants();
            ViewBag.ProdId = GetProducts();
            SelectList categories = new SelectList(Enum.GetValues(typeof(BaseCategories)));
            ViewBag.Categories = categories;
            return View(menu);
        }

        public async Task<IActionResult> Details(int id)
        {
            var menuDetail = await _service.GetById(id);
            return View(menuDetail);
        }

        [Authorize]
        [HttpGet]
        public async Task<IActionResult> Edit(int id)
        {
            var menuDetails = await _service.GetById(id);

            var response = new CreateMenuVM()
            {
                Id = menuDetails.Id,
                Name = menuDetails.Name,
                Price = menuDetails.Price,
                PictureURL = menuDetails.PictureURL,
                Category = menuDetails.Category,
                RestaurantId = menuDetails.RestaurantId,
                ProductIds = menuDetails.Products_Menues.Select(m => m.ProductId).ToList()
            };

            ViewBag.RestId = GetRestaurants();
            ViewBag.ProdId = GetProducts();
            SelectList categories = new SelectList(Enum.GetValues(typeof(BaseCategories)));
            ViewBag.Categories = categories;
            return View(response);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(CreateMenuVM menu)
        {
            if (ModelState.IsValid)
            {
                await _service.Update(menu);
                return RedirectToAction(nameof(Index));
            }
            ViewBag.RestId = GetRestaurants();
            ViewBag.ProdId = GetProducts();
            SelectList categories = new SelectList(Enum.GetValues(typeof(BaseCategories)));
            ViewBag.Categories = categories;
            return View(menu);
        }

        public async Task<IActionResult> Delete(int id)
        {
            await _service.Delete(id);
            return RedirectToAction(nameof(Index));
        }
    }
}

Web_Project/Controllers/ProductController.cs
using BusinessLogic.Services;
using DataLayer.Entityes;
using DataLayer.Enums;
using DataLayer.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace Web_Project.Controllers
{
    public class ProductController : Controller
    {   
        private readonly IProductService _service;

        public ProductController(IProductService service)
        {
            _service = service;
        }
        public async Task<IActionResult> Index()
        {
            var products = await _service.GetAll();
            return View(products);
        }

        //Get: Product/Create
        public IActionResult Create()
        {
            SelectList categories = new SelectList(Enum.GetValues(typeof(ProductCategories)));
            ViewBag.Categories = categories;
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create([Bind("Id, Name, PictureURL, Description, Category, Price")]Product product)
        {
            if (ModelState.IsValid)
            {
                await _service.Add(product);
                return RedirectToAction(nameof(Index));
            }
            SelectList categories = new SelectList(Enum.GetValues(typeof(ProductCategories)));
            ViewBag.Categories = categories;
            return View(product);
        }

        [HttpGet]
        public async Task<IActionResult> Edit(int id)
        {
            var productDetails = await _service.GetById(id);

            var response = new Product()
            {
                Id = productDetails.Id,
                Name = productDetails.Name,
                PictureURL = productDetails.PictureURL,
                Description = productDetails.Description,
                Category = productDetails.Category,
                Price = productDetails.Price,
            };

            SelectList categories = new SelectList(Enum.GetValues(typeof(ProductCategories)));
            ViewBag.Categories = categories;
            return View(response);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(Product product)
        {
            if (ModelState.IsValid)
            {
                await _service.Update(product);
                return RedirectToAction(nameof(Index));
            }

            SelectList categories = new SelectList(Enum.GetValues(typeof(ProductCategories)));
            ViewBag.Categories = categories;
            return View(product);
        }

        public async Task<IActionResult> Details(int id)
        {
            var productDetail = await _service.GetById(id);
            return View(productDetail);
        }

        public async Task<IActionResult> Delete(int id)
        {
            await _service.Delete(id);
            return RedirectToAction(nameof(Index));
        }
    }
}

Web_Project/Controllers/RestaurantController.cs
using BusinessLogic.Services;
using DataLayer.Entityes;
using DataLayer.Enums;
using Microsoft.AspNetCore.Mvc;
using System.Dynamic;

namespace Web_Project.Controllers
{
    public class RestaurantController : Controller
    {
        private readonly IRestaurantService _service;

        public RestaurantController(IRestaurantService service)
        {
            _service = service;
        }
        public async Task<IActionResult> Index()
        {
            var restaurants = await _service.GetAll();
            return View(restaurants);
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(Restaurant restaurant)
        {
            if (ModelState.IsValid)
            {
                await _service.Add(restaurant);
                return RedirectToAction(nameof(Index));
            }
            return View(restaurant);
        }

        [HttpGet]
        public async Task<IActionResult> Edit(int id)
        {
            var restaurantDetails = await _service.GetById(id);

            var response = new Restaurant()
            {
                Id = restaurantDetails.Id,
                Name = restaurantDetails.Name,
                PictureURL = restaurantDetails.PictureURL,
                Category = restaurantDetails.Category,
            };

            return View(response);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(Restaurant restaurant)
        {
            if (ModelState.IsValid)
            {
                await _service.Update(restaurant);
                return RedirectToAction(nameof(Index));
            }

            return View(restaurant);
        }

        [HttpGet]
        public async Task<IActionResult> Details(int id)
        {
            dynamic model = new ExpandoObject();
            model.Restaurant = await _service.GetAsList(id);
            model.Menu = await _service.GetAllMenues();
            return View(model);
        }

        public async Task<IActionResult> Delete(int id)
        {
            await _service.Delete(id);
            return RedirectToAction(nameof(Index));
        }
    }
}

Web_Project/Controllers/UserController.cs
using BusinessLogic.Services.User;
using DataLayer.User;
using DataLayer.ViewModels;
using Microsoft.AspNetCore.Mvc;

namespace Web_Project.Controllers
{
    public class UserController : Controller
    {
        private readonly IUserService _service;
        public UserController(IUserService service)
        {
            _service = service;
        }

        [HttpGet]
        public IActionResult Register()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Register(CreateUserVM user) 
        {
            try
            {
                if (ModelState.IsValid)
                {
                    await _service.AddUser(user);
                    await _service.AddCart(user);
                    return RedirectToAction(nameof(Login), new { wasRedirected = true });
                }
                //Implement Token

                return View(user);
            }catch(Exception error) 
            {
                ViewData["Error"] = error.Message;
                return View(user);
            }
        }

        [HttpGet]
        public IActionResult Login(bool? wasRedirected)
        {
            if (wasRedirected == true)
            {
                ViewData["Register"] = "Succesfully Registered";
            }
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Login(LoginUserVM user)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    UserData UserExist = await _service.CheckUser(user);
                    UserData data = await _service.CheckEmail(user.Email);
                    var token = _service.GenerateToken(data);
                    HttpContext.Response.Cookies.Append("Authorization", token, new CookieOptions { HttpOnly = true, Secure = true });
                    return RedirectToAction("Index", "Home", new { wasRedirected = true });
                }
                //Implement Token

                return View(user);
            }catch(Exception error)
            {
                ViewData["Error"] = error.Message;
                return View(user);
            }
        }

        public IActionResult Logout()
        {
            HttpContext.Response.Cookies.Delete("Authorization");
            return RedirectToAction("Index", "Home");
        }

        public async Task<IActionResult> Users()
        {
            var users = await _service.GetAll();
            return View(users);

        }

    }
}

Web_Project/Views/Shared/_Layout.cshtml
<!DOCTYPE html>



<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Twins</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Web_Project.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.3/font/bootstrap-icons.css">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Twins</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" 
                aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
@*                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>*@
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Product" asp-action="Index">Products</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Menu" asp-action="Index">Menues</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Restaurant" asp-action="Index">Restaurants</a>
                        </li>

                        @*<li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                <i class="badge-info bi-gear"></i> Management
                            </a>

                            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <a class="dropdown-item" asp-controller="User" asp-action="Users">Users</a>
                            </div>
                        </li>*@
                    </ul>
                    <partial name="_UserBar.cshtml" />

                </div>
            </div>
        </nav>
    </header>
    <div class="container-fluid">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Twins - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Web_Project/Views/Shared/_UserBar.cshtml
@using System.IdentityModel.Tokens.Jwt;
<!DOCTYPE html>
@{
    string token;
    Context.Request.Cookies.TryGetValue("Authorization", out token);
}

@if (token == null)
{
    <div class="form-group">
        <a class="btn btn-outline-success float-right" asp-controller="User" asp-action="Login">Login</a>
        <a class="btn btn-outline-secondary" asp-controller="User" asp-action="Register">New User?</a>
    </div>
}
else
{
    var handler = new JwtSecurityTokenHandler();
    var jsonToken = handler.ReadToken(token);
    var tokenS = jsonToken as JwtSecurityToken;
    string username = tokenS.Claims.First(claim => claim.Type == "sub").Value;
    string role = tokenS.Claims.First(claim => claim.Type == "Role").Value;

    @*User profile section*@
    <div class="nav-item dropdown">
        <button class="btn btn-outline-success dropdown-toggle" type="button" id="profile-btn" data-toggle="dropdown" data-bs-toggle="dropdown"
            aria-expanded="false">
            <i class="bi bi-person-badge"></i> Hello @username
        </button>

        @if (role == "admin")
        {
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <a class="dropdown-item" asp-controller="User" asp-action="Users">Users</a>
            </div>
        }
        else
        {
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <a class="dropdown-item" asp-controller="Cart" asp-action="Index"><i class="bi bi-cart4"></i>Shopping Cart</a>
            </div>
        }

    </div>
    

    <span style="padding: 5px;"></span>
    <form asp-controller="User" asp-action="Logout">
        <button class="btn btn-outline-danger my-2 my-sm-0">
            <i class="bi bi-box-arrow-in-right"></i> Log out
        </button>
    </form>
}